### ISSUE TITLE
Mudança no site do php-pb

### ISSUE THREAD

**Issue by antoniojeremias** [php-pb/php-pb.github.io#38]
Após algumas conversas com o @vicentimartins sobre algumas possíveis mudanças no site do php-pb entramos numa discussão que achamos interessante trazer pra comunidade para que rolasse uma espécie de brainstorming para responder a seguinte questão: **qual seria a melhor opção de tecnologia ou plataforma para o site da nossa comunidade?**

Algumas sugestões:
- Continuar com o [Jekyll](https://jekyllrb.com/)
- Migrar para o [Spress - The static site generator in PHP](http://spress.yosymfony.com/)
- Migrar para o [Medium](https://medium.com/)

**Comment by vicentimartins** [comment]
Eu curto muito o lance do medium. Já possui toda infra levando o autor a, apenas, escrever o texto e direciona para um público com interesse no assunto.

#medium

**Comment by jammersonf** [comment]
Também voto no Medium

**Comment by vicentimartins** [comment]
Dadas as alterações no modelo de negócio do medium, não migrar nosso blogo pra lá acabou sendo bom.
Sobre mudar o site, hoje não vejo a necessidade, dado que o espaço está sendo usado muito pouco, então a tech que construirmos ele não vai mudar nada. O foco deveria ser movimentar o blog.
